# Generated by Django 5.0.4 on 2025-02-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='wallet',
            field=models.TextField(max_length=100),
        ),
    ]
